/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2022-08-11 02:34:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>TutorFinder</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Facebook Opengraph integration: https://developers.facebook.com/docs/sharing/opengraph -->\r\n");
      out.write("  <meta property=\"og:title\" content=\"\">\r\n");
      out.write("  <meta property=\"og:image\" content=\"\">\r\n");
      out.write("  <meta property=\"og:url\" content=\"\">\r\n");
      out.write("  <meta property=\"og:site_name\" content=\"\">\r\n");
      out.write("  <meta property=\"og:description\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Twitter Cards integration: https://dev.twitter.com/cards/  -->\r\n");
      out.write("  <meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("  <meta name=\"twitter:site\" content=\"\">\r\n");
      out.write("  <meta name=\"twitter:title\" content=\"\">\r\n");
      out.write("  <meta name=\"twitter:description\" content=\"\">\r\n");
      out.write("  <meta name=\"twitter:image\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("   <link href=\"assets-welcome/img/logo-tfs-no-text.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"assets-welcome/img/logo-tfs-no-text.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"assets-welcome/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets-welcome/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets-welcome/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets-welcome/vendor/glightbox/css/glightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets-welcome/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"assets-welcome/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: Imperial - v5.7.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/imperial-free-onepage-bootstrap-theme/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("  <style>\r\n");
      out.write("\r\n");
      out.write("    /**\r\n");
      out.write("* Template Name: Imperial - v5.7.0\r\n");
      out.write("* Template URL: https://bootstrapmade.com/imperial-free-onepage-bootstrap-theme/\r\n");
      out.write("* Author: BootstrapMade.com\r\n");
      out.write("* License: https://bootstrapmade.com/license/\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("/*--------------------------------------------------------------\r\n");
      out.write("# General\r\n");
      out.write("--------------------------------------------------------------*/\r\n");
      out.write("body {\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  color: #AC20CD;\r\n");
      out.write("  font-family: \"Open Sans\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: #03C4EB;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover, a:active, a:focus {\r\n");
      out.write("  color: #03c5ec;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  margin: 0 0 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1, h2, h3, h4, h5, h6 {\r\n");
      out.write("  font-family: \"Raleway\", sans-serif;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  margin: 0 0 20px 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Prelaoder */\r\n");
      out.write("#preloader {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  z-index: 999;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  overflow: visible;\r\n");
      out.write("  background: #fff url(\"../img/preloader.svg\") no-repeat center center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*--------------------------------------------------------------\r\n");
      out.write("# Welcome\r\n");
      out.write("--------------------------------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 1024px) {\r\n");
      out.write("  #hero {\r\n");
      out.write("    background-attachment: fixed;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("#hero .hero-logo {\r\n");
      out.write("  margin: 20px;\r\n");
      out.write("}\r\n");
      out.write("#hero .hero-logo img {\r\n");
      out.write("  max-width: 150px;\r\n");
      out.write("}\r\n");
      out.write("#hero .hero-container {\r\n");
      out.write("  background: rgba(98, 29, 138, 0.582);\r\n");
      out.write("  display: table-cell;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding-top: 80px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  vertical-align: auto;\r\n");
      out.write("}\r\n");
      out.write("#hero h1 {\r\n");
      out.write("  margin: 30px 0 10px 0;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  line-height: 48px;\r\n");
      out.write("  letter-spacing: 6px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  #hero h1 {\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("    line-height: 36px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("#hero h2 {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("  margin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("#hero h2 span {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  border-bottom: 2px solid #03C4EB;\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  #hero h2 {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    line-height: 26px;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  #hero h2 .rotating {\r\n");
      out.write("    display: block;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("#hero .rotating > .animated {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("#hero .actions a {\r\n");
      out.write("  font-family: \"Raleway\", sans-serif;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  letter-spacing: 1px;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding: 8px 20px;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("#hero .btn-welcome {\r\n");
      out.write("  background: #9b55c9c2;\r\n");
      out.write("  border: 2px solid rgba(255, 255, 255, 0.562);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  width:150px;\r\n");
      out.write("}\r\n");
      out.write("#hero .btn-welcome:hover {\r\n");
      out.write("  background: none;\r\n");
      out.write("  border: 2px solid #fff;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  width:150px;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Hero Section ======= -->\r\n");
      out.write("  <section id=\"hero\">\r\n");
      out.write("    <div class=\"hero-container\">\r\n");
      out.write("      <div data-aos=\"fade-in\">\r\n");
      out.write("        <div class=\"hero-logo\">\r\n");
      out.write("          <img class=\"\" src=\"assets-welcome/img/logo-tfs-no-text.png\" alt=\"TutorFinder\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h1>TutorFinder</h1>\r\n");
      out.write("      <h2>We serve connection among Tutors and Students</h2>\r\n");
      out.write("      <div class=\"d-block m-0 text-white\">\r\n");
      out.write("        <h4>Select Your Role</h4>\r\n");
      out.write("        <div class=\"actions\">\r\n");
      out.write("          <a href=\"StuLoginPathFirst.do\" class=\"btn-welcome\">Student</a>\r\n");
      out.write("          <a href=\"loginPathFirst.do\" class=\"btn-welcome\">Tutor</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section><!-- End Hero -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"assets-welcome/vendor/aos/aos.js\"></script>\r\n");
      out.write("  <script src=\"assets-welcome/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets-welcome/vendor/glightbox/js/glightbox.min.js\"></script>\r\n");
      out.write("  <script src=\"assets-welcome/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"assets-welcome/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets-welcome/vendor/typed.js/typed.min.js\"></script>\r\n");
      out.write("  <script src=\"assets-welcome/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"assets-welcome/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
